name: example

on: [ push, pull_request ]

jobs:

  runner:

    runs-on: ubuntu:20.04 # 选择你想要的主机系统如：ubuntu:20.04

    steps:

      - uses: actions/checkout@v3

      - name: collie

        uses: dvkunion/CollieTrickster@main

        with:

          token: 54db7d0191bf2e044cd2a3ebb6142b41  # your token,  It will be safer to use ${{ secrets.token }}, see [https://docs.github.com/actions/security-guides/encrypted-secrets] 
